apiVersion: 1

datasources:
  - name: InfluxDB
    isDefault: true
    type: influxdb
    access: proxy
    url: http://$INFLUXDB_HOST:$INFLUXDB_PORT
    secureJsonData:
      token: $INFLUXDB_TOKEN
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: $INFLUXDB_BUCKET
      tlsSkipVerify: true